name: Uptime Monitor

on:
  workflow_dispatch: # Permite execução manual
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Fix Cypress permissions
        run: chmod +x ./node_modules/.bin/cypress


      - name: Executar testes Cypress
        run: npx cypress run
        env:
          CYPRESS_EMAIL_USER: ${{ secrets.EMAIL_USER }}
          CYPRESS_EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
